version: '3.8'

services:
  db:
    container_name: postgres
    build: 
      context: ./db
      dockerfile: db.Dockerfile
    ports:
        - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  server:
    container_name: server
    build: 
      context: ./server
      dockerfile: node.Dockerfile
    depends_on:
      - db
    ports: 
      - "3001:3001"
    volumes:
      - .:/server